apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
   name: postgres-service
   app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    app: postgres-app
    type: front-end
  ports:
  - port: 5432
    targetPort: 5432