apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
   name: result-app
   app: demo-voting-app
spec:
  type: NodePort
  selector:
    app: result-app
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006