apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: busybox1
    type: nginx-frontend
spec:
 template:
  metadata:
   name: new-replica-set
   labels:
     app: busybox1
     type: nginx-frontend
  spec:
    containers:
     - name: busybox-container
       image: busybox
 replicas: 4
 selector:
   matchLabels:
       type: nginx-frontend
     
     