apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-app
 labels:
   app: nginx-app
spec:
  template:
   metadata:
    name: nginx-app-pod
    labels:
     app: nginx-app
   spec:
    containers:
     - name: nginx-app
       image: nginx:1.16
  replicas: 3
  selector:
      matchLabels:
       app: nginx-app

     
    