apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongodb
 labels:
   app: mongodb
spec:
  replicas: 2
  selector:
   matchLabels:
     app: mongodb
    
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo
