apiVersion: v1
kind: Pod
metadata:
 name: nginx-resource
 labels:
  name: nginx-resource
  type: frontend
spec:
  containers:
    - name: nginx-frontend
      image: nginx
      resources:
       limits:
        memory: 512Mi
        cpu: "1"
       requests:
        memory: 256Mi
        cpu: "0.2"