apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    tier: db
spec:
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      name: postgres-pod
      labels:
        tier: db
    spec:
      containers:
      - name: postgres-container
        image: postgresql
  replicas: 3
