apiVersion: v1
kind: Service
metadata:
 name:  apptestservice
 labels:
   app: testapp
spec:
  selector:
    app:  testapp
  type:  NodePort
  ports:
  - name:  nginx
    port:  80
    targetPort:  80
    nodePort: 31000
  
