apiVersion: apps/v1
kind: Deployment
metadata:
   name: httpd-deployment
   labels:
     app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 4
  template:
    metadata:
      name: my-httpd
      labels:
        app: web
    spec:
      containers:
        - name: httpd-deployment
          image: httpd