apiVersion: v1
kind: Pod
metadata:
   name: voting-app
   labels:
    app: voting-app
    type: front-end
spec:
    containers:
       - name: voting-app
         image: kodekloud/examplvotingapp_vote:v1
         ports:
          - containerPort: 80