apiVersion: v1
kind: Pod
metadata:
    name: worker-app
    labels: 
     app: worker-app
     type: front-end
spec:
    containers:
       - name: worker-app
         image: kodekloud/examplvotingapp_worker:v1