apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  selector:
   name: voting-app-pod
   app: demo-voting-app  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000

