apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgres-app
   labels:
    app: postgres-app
    type: front-end
spec:
    replicas: 3
    selector:
      matchLabels:
        app: postgres-app
        type: front-end
    template:
      metadata:
        name: postgres-app
        labels:
          app: postgres-app
          type: front-end
      spec:
          containers:
            - name:  postgres-app
              image: postgres
              ports:
              - containerPort: 5432
              env:
                - name: POSTGRES_USER
                  value: "postgres"
                - name: POSTGRES_PASSWORD
                  value: "postgres"
        