apiVersion: apps/v1
kind: Deployment
metadata:
   name: redis-app
   labels:
    app: redis-app
    type: front-end
spec:
    replicas: 3
    selector:
      matchLabels:
        app: redis-app
        type: front-end
    template:
      metadata:
        name: redis-app
        labels:
          app: redis-app
          type: front-end
      spec:
          containers:
            - name:  redis-app
              image: redis
              ports:
              - containerPort: 6379