apiVersion: v1
kind: Pod
metadata:
   name: workerpod
   labels:
     name: worker-app-pod
     app: demo-voting-app
spec:
  containers:
    - name: worker-app-container
      image: worker
      imagePullPolicy: IfNotPresent
   